### ISSUE TITLE
Add licence file

### ISSUE THREAD

**Issue by KirstieJane** [BulliedIntoBadScience/logos#1]
This is such a great repo - I love the logos and the fact that you have so many different versions!!

Would it make sense to add a LICENCE file to the repository to make clear who can use these logos and for what?

I’d be happy to add the file - I’m just not sure what limitations you’d like to add to reuse 😄

**Comment by lgatto** [comment]
Thank you Kirstie, excellent point. I'm checking with @corinalogan re preferred license.

**Comment by lgatto** [comment]
Thanks again @KirstieJane - we have opted for a CC-BY-SA license.

**Comment by KirstieJane** [comment]
Coolio! It might be worth being clear who the re-user should acknowledge. Is it the artist or Bullied into Bad Science?

**Comment by lgatto** [comment]
Yes, excellent suggestion indeed, which I have addressed now. Thanks again!
